CREATE TABLE [dbo].[t_cat_tipo_solicitud_servicio] (
    [PK_TIPO_SOLICITUD_SERVICIO] INT            IDENTITY (1, 1) NOT NULL,
    [PK_SERVICIO_REQUERIDO]      INT            NOT NULL,
    [DESCRIPCION]                NVARCHAR (100) NULL,
    CONSTRAINT [PK_T_CAT_TIPO_SOLICITUD_SERVICIO] PRIMARY KEY CLUSTERED ([PK_TIPO_SOLICITUD_SERVICIO] ASC, [PK_SERVICIO_REQUERIDO] ASC),
    CONSTRAINT [FK_T_CAT_TIPO_SOLICITUD_SERVICIO_T_CAT_SERVICIO_REQUERIDO] FOREIGN KEY ([PK_SERVICIO_REQUERIDO]) REFERENCES [dbo].[t_cat_servicio_requerido] ([PK_SERVICIO_REQUERIDO])
);

