CREATE TABLE [dbo].[t_cat_tipo_averia] (
    [PK_TIPO_AVERIA] INT            IDENTITY (1, 1) NOT NULL,
    [DESCRIPCION]    NVARCHAR (100) NULL,
    [STATUS]         BIT            NOT NULL,
    CONSTRAINT [PK_T_CAT_TIPO_AVERIA] PRIMARY KEY CLUSTERED ([PK_TIPO_AVERIA] ASC)
);



