CREATE TABLE [dbo].[t_cat_naturaleza_inmueble] (
    [PK_NATURALEZA_INMUEBLE] INT            IDENTITY (1, 1) NOT NULL,
    [DESCRIPCION]            NVARCHAR (100) NULL,
    CONSTRAINT [PK_T_CAT_NATURALEZA_INMUEBLE] PRIMARY KEY CLUSTERED ([PK_NATURALEZA_INMUEBLE] ASC)
);

