CREATE TABLE [dbo].[t_cat_tipo_titular_inmueble] (
    [PK_TIPO_TITULAR_INMUEBLE] INT            IDENTITY (1, 1) NOT NULL,
    [DESCRIPCION]              NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_T_CAT_TIPO_TITULAR_INMUEBLE] PRIMARY KEY CLUSTERED ([PK_TIPO_TITULAR_INMUEBLE] ASC)
);

