CREATE TABLE [dbo].[t_cat_tipo_Proyecto] (
    [PK_TIPO_PROYECTO] INT            IDENTITY (1, 1) NOT NULL,
    [DESCRIPCION]      NVARCHAR (100) NULL,
    CONSTRAINT [PK_T_CAT_TIPO_PROYECTO] PRIMARY KEY CLUSTERED ([PK_TIPO_PROYECTO] ASC)
);

