CREATE TABLE [dbo].[t_ges_gestion] (
    [PK_GESTION]        INT            IDENTITY (1, 1) NOT NULL,
    [FK_ADMIN_GESTION]  INT            NOT NULL,
    [FK_USUARIO]        INT            NOT NULL,
    [NOSOLICITUD]       NVARCHAR (100) NULL,
    [FECHAPRESENTACION] DATE           NULL,
    CONSTRAINT [PK_T_GES_GESTION] PRIMARY KEY CLUSTERED ([PK_GESTION] ASC),
    CONSTRAINT [FK_T_GES_GESTION_T_CAT_ADMIN_GESTION] FOREIGN KEY ([FK_ADMIN_GESTION]) REFERENCES [dbo].[t_cat_admin_gestion] ([PK_ADMIN_GESTION]),
    CONSTRAINT [FK_T_GES_GESTION_T_SEG_USUARIO] FOREIGN KEY ([FK_USUARIO]) REFERENCES [seguridad].[t_seg_usuario] ([PK_USUARIO])
);

