CREATE TABLE [dbo].[t_ges_devolucion] (
    [PK_DEVOLUCION]            INT             NOT NULL,
    [FK_TIPO_IDENTIFICACION]   INT             NULL,
    [FK_TIPO_TITULAR_INMUEBLE] INT             NULL,
    [NOMBRE]                   NVARCHAR (20)   NULL,
    [P_APELLIDO]               NVARCHAR (20)   NULL,
    [S_APELLIDO]               NVARCHAR (20)   NULL,
    [TIPO_SOLICITANTE]         CHAR (1)        NOT NULL,
    [NIS]                      INT             NULL,
    [NOMBRE_TITULAR]           NVARCHAR (50)   NULL,
    [IDENTIFICACION]           VARBINARY (MAX) NULL,
    CONSTRAINT [PK_T_GES_DEVOLUCION] PRIMARY KEY CLUSTERED ([PK_DEVOLUCION] ASC),
    CONSTRAINT [CHK_TIPO_SOLICITANTE_T_GES_ARREGLO_PAGO] CHECK ([TIPO_SOLICITANTE]='T' OR [TIPO_SOLICITANTE]='R' OR [TIPO_SOLICITANTE]='S'),
    CONSTRAINT [FK_T_GES_DEVOLUCION_T_CAT_TIPO_IDENTIFICACION] FOREIGN KEY ([FK_TIPO_IDENTIFICACION]) REFERENCES [dbo].[t_cat_tipo_identificacion] ([PK_TIPO_IDENTIFICACION]),
    CONSTRAINT [FK_T_GES_DEVOLUCION_T_GES_GESTION] FOREIGN KEY ([PK_DEVOLUCION]) REFERENCES [dbo].[t_ges_gestion] ([PK_GESTION])
);

