CREATE TABLE [dbo].[t_ges_arreglo_pago] (
    [PK_ARREGLO_PAGO]        INT             NOT NULL,
    [FK_TIPO_IDENTIFICACION] INT             NULL,
    [NOMBRE_USUARIO]         NVARCHAR (100)  NULL,
    [NOMBRE_SOLICITANTE]     NVARCHAR (15)   NULL,
    [P_APELLIDO_SOLICITANTE] NVARCHAR (15)   NULL,
    [S_APELLIDO_SOLICITANTE] NVARCHAR (15)   NULL,
    [EMAIL]                  NVARCHAR (100)  NULL,
    [CELULAR]                NVARCHAR (9)   NULL,
    [TELEFONO]               NVARCHAR (9)   NULL,
    [TIPOPERSONA]            CHAR (1)        NOT NULL,
    [OBSERVACIONES]          NVARCHAR (500)  NULL,
    [URL_IDENTIFICACION]         NVARCHAR (250) NULL,
    [STATUS]                 BIT             NOT NULL,
    CONSTRAINT [PK_T_GES_ARREGLO_PAGO] PRIMARY KEY CLUSTERED ([PK_ARREGLO_PAGO] ASC),
    CONSTRAINT [CHK_TIPOPERSONA_T_GES_ARREGLO_PAGO] CHECK ([TIPOPERSONA]='J' OR [TIPOPERSONA]='F'),
    CONSTRAINT [FK_T_GES_ARREGLO_PAGO_T_CAT_TIPO_IDENTIFICACION] FOREIGN KEY ([FK_TIPO_IDENTIFICACION]) REFERENCES [dbo].[t_cat_tipo_identificacion] ([PK_TIPO_IDENTIFICACION]),
    CONSTRAINT [FK_T_GES_ARREGLO_PAGO_T_GES_GESTION] FOREIGN KEY ([PK_ARREGLO_PAGO]) REFERENCES [dbo].[t_ges_gestion] ([PK_GESTION])
);



