CREATE TABLE [dbo].[t_ges_reclamo_importe] (
    [PK_RECLAMO_IMPORTE]     INT             NOT NULL,
    [FK_TIPO_IDENTIFICACION] INT             NULL,
    [FK_CALIDAD_SOLICITANTE] INT             NULL,
    [FK_PRETENSION]          INT             NULL,
    [NOMBRE]                 NVARCHAR (20)   NULL,
    [P_APELLIDO]             NVARCHAR (20)   NULL,
    [S_APELLIDO]             NVARCHAR (20)   NULL,
    [IDENTIFICACION]         NVARCHAR (20)   NULL,
    [NIS]                    INT             NULL,
    [NOMBRE_TITULAR]         NVARCHAR (50)   NULL,
    [FACTURAS_RECLAMADAS]    NVARCHAR (100)  NULL,
    [SOLICITUD]              NVARCHAR (1000) NULL,
    [OTRO]                   NVARCHAR (100)  NULL,
    [STATUS]                 BIT             DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_GES_RECLAMO_IMPORTE] PRIMARY KEY CLUSTERED ([PK_RECLAMO_IMPORTE] ASC),
    CONSTRAINT [FK_T_GES_RECLAMO_IMPORTE_T_CAT_CALIDAD_SOLICITANTE] FOREIGN KEY ([FK_CALIDAD_SOLICITANTE]) REFERENCES [dbo].[t_cat_calidad_solicitante] ([PK_CALIDAD_SOLICITANTE]),
    CONSTRAINT [FK_T_GES_RECLAMO_IMPORTE_T_CAT_PRETENSION] FOREIGN KEY ([FK_PRETENSION]) REFERENCES [dbo].[t_cat_pretension] ([PK_PRETENSION]),
    CONSTRAINT [FK_T_GES_RECLAMO_IMPORTE_T_CAT_TIPO_IDENTIFICACION] FOREIGN KEY ([FK_TIPO_IDENTIFICACION]) REFERENCES [dbo].[t_cat_tipo_identificacion] ([PK_TIPO_IDENTIFICACION]),
    CONSTRAINT [FK_T_GES_RECLAMO_IMPORTE_T_GES_GESTION] FOREIGN KEY ([PK_RECLAMO_IMPORTE]) REFERENCES [dbo].[t_ges_gestion] ([PK_GESTION])
);

