CREATE TABLE [dbo].[t_ges_constancia_servicio_existente] (
    [PK_CONSTANCIA_SERVICIO_EXISTENTE]  INT            NOT NULL,
    [NIS]                               INT            NULL,
    [FK_NATURALEZA_INMUEBLE]            INT            NULL,
    [FK_TITULO_PROPIEDAD]               INT            NULL,
    [FOLIO_MATRICULA]                   NVARCHAR (20)  NULL,
    [NODOCUMENTO]                       NVARCHAR (20)  NULL,
    [FK_TIPO_DATOS_SOLICITANTE]         INT            NULL,
    [NOMBRE]                            NVARCHAR (15)  NULL,
    [PRIMERAPELLIDO]                    NVARCHAR (15)  NULL,
    [SEGUNDOAPELLIDO]                   NVARCHAR (15)  NULL,
    [FK_TIPO_IDENTIFICACION]            INT            NULL,
    [CEDULA_FISICA]                     NVARCHAR (10)  NULL,
    [DIMEX]                             NVARCHAR (12)  NULL,
    [PASAPORTE]                         NVARCHAR (20)  NULL,
    [TELEFONO1]                         NVARCHAR (20)  NOT NULL,
    [TELEFONO2]                         NVARCHAR (20)  NULL,
    [EMAIL]                             NVARCHAR (100) NULL,
    [RAZON_SOCIAL]                      NVARCHAR (50)  NULL,
    [CEDULA_JURIDICA]                   NVARCHAR (15)  NULL,
    [FK_OBJETIVO_CONSTANCIA]            INT            NULL,
    [JUSTIFICACION_OBJETIVO_CONSTANCIA] NVARCHAR (250) NULL,
    [URL_DOC_IDENTIFICACION]            NVARCHAR (250) NULL,
    [STATUS]                            BIT            NULL,
    CONSTRAINT [PK_t_ges_constancia_servicio_existente] PRIMARY KEY CLUSTERED ([PK_CONSTANCIA_SERVICIO_EXISTENTE] ASC),
    CONSTRAINT [FK_t_ges_constancia_servicio_existente_t_cat_naturaleza_inmueble] FOREIGN KEY ([FK_NATURALEZA_INMUEBLE]) REFERENCES [dbo].[t_cat_naturaleza_inmueble] ([PK_NATURALEZA_INMUEBLE]),
    CONSTRAINT [FK_t_ges_constancia_servicio_existente_t_cat_objetivo_constancia] FOREIGN KEY ([FK_OBJETIVO_CONSTANCIA]) REFERENCES [dbo].[t_cat_objetivo_constancia] ([PK_OBJETIVO_CONSTANCIA]),
    CONSTRAINT [FK_t_ges_constancia_servicio_existente_t_cat_tipo_datos_solicitante] FOREIGN KEY ([FK_TIPO_DATOS_SOLICITANTE]) REFERENCES [dbo].[t_cat_tipo_datos_solicitante] ([PK_TIPO_DATOS_SOLICITANTE]),
    CONSTRAINT [FK_t_ges_constancia_servicio_existente_t_cat_tipo_identificacion] FOREIGN KEY ([FK_TIPO_IDENTIFICACION]) REFERENCES [dbo].[t_cat_tipo_identificacion] ([PK_TIPO_IDENTIFICACION]),
    CONSTRAINT [FK_t_ges_constancia_servicio_existente_t_cat_titulo_propiedad] FOREIGN KEY ([FK_TITULO_PROPIEDAD]) REFERENCES [dbo].[t_cat_titulo_propiedad] ([PK_TITULO_PROPIEDAD]),
    CONSTRAINT [FK_t_ges_constancia_servicio_existente_t_ges_gestion] FOREIGN KEY ([PK_CONSTANCIA_SERVICIO_EXISTENTE]) REFERENCES [dbo].[t_ges_gestion] ([PK_GESTION])
);

