CREATE TABLE [dbo].[t_ges_informacion_titular] (
    [PK_INFORMACION_TITULAR]   INT            NOT NULL,
    [FK_TIPO_TITULAR_INMUEBLE] INT            NOT NULL,
    [TIPOPERSONA]              CHAR (1)       NOT NULL,
    [NOMBRE]                   NVARCHAR (10)  NULL,
    [P_APELLIDO]               NVARCHAR (50)  NULL,
    [S_APELLIDO]               NVARCHAR (50)  NULL,
    [RAZONSOCIAL]              NVARCHAR (100) NULL,
    [IDENTIFICACION]           NVARCHAR (50)  NULL,
    CONSTRAINT [PK_T_GES_INFORMACION_TITULAR] PRIMARY KEY CLUSTERED ([PK_INFORMACION_TITULAR] ASC),
    CONSTRAINT [CHK_TIPOPERSONA_T_GES_INFORMACION_TITULAR] CHECK ([TIPOPERSONA]='J' OR [TIPOPERSONA]='F'),
    CONSTRAINT [FK_T_GES_INFORMACION_TITULAR_T_CAT_TIPO_TITULAR_INMUEBLE] FOREIGN KEY ([FK_TIPO_TITULAR_INMUEBLE]) REFERENCES [dbo].[t_cat_tipo_titular_inmueble] ([PK_TIPO_TITULAR_INMUEBLE]),
    CONSTRAINT [FK_T_GES_INFORMACION_TITULAR_T_GES_GESTION] FOREIGN KEY ([PK_INFORMACION_TITULAR]) REFERENCES [dbo].[t_ges_gestion] ([PK_GESTION])
);

