CREATE TABLE [dbo].[t_ges_nuevo_servicio] (
    [PK_NUEVO_SERVICIO]          INT NOT NULL,
    [PK_SERVICIO_REQUERIDO]      INT NOT NULL,
    [FK_TIPO_SOLICITUD_SERVICIO] INT NULL,
    [FK_FORMA_CANCELACION]       INT NULL,
    [AGUA_RESIDUAL]              BIT NULL,
    [TIENE_NIS]                  BIT NULL,
    [NIS]                        NVARCHAR(7),
    [CODIGO_APC]                 INT NULL,
    [NO_DISPONIBILIDAD_PREVIA]   NVARCHAR(20),
    [STATUS]                     BIT NOT NULL,
    CONSTRAINT [PK_T_GES_NUEVO_SERVICIO] PRIMARY KEY CLUSTERED ([PK_NUEVO_SERVICIO] ASC, [PK_SERVICIO_REQUERIDO] ASC),
    CONSTRAINT [FK_T_GES_NUEVO_SERVICIO_T_CAT_FORMA_CANCELACION] FOREIGN KEY ([FK_FORMA_CANCELACION]) REFERENCES [dbo].[t_cat_forma_cancelacion] ([PK_FORMA_CANCELACION]),
    CONSTRAINT [FK_T_GES_NUEVO_SERVICIO_T_CAT_SERVICIO_REQUERIDO] FOREIGN KEY ([PK_SERVICIO_REQUERIDO]) REFERENCES [dbo].[t_cat_servicio_requerido] ([PK_SERVICIO_REQUERIDO]),
    CONSTRAINT [FK_T_GES_NUEVO_SERVICIO_T_CAT_TIPO_SOLICITUD_SERVICIO] FOREIGN KEY ([FK_TIPO_SOLICITUD_SERVICIO], [PK_SERVICIO_REQUERIDO]) REFERENCES [dbo].[t_cat_tipo_solicitud_servicio] ([PK_TIPO_SOLICITUD_SERVICIO], [PK_SERVICIO_REQUERIDO]),
    CONSTRAINT [FK_t_ges_nuevo_servicio_t_ges_gestion] FOREIGN KEY ([PK_NUEVO_SERVICIO]) REFERENCES [dbo].[t_ges_gestion] ([PK_GESTION])
);



