CREATE TABLE [dbo].[t_srv_reporte_averia] (
    [PK_REPORTE_AVERIA] INT            IDENTITY (1, 1) NOT NULL,
    [FK_PROVINCIA]      INT            NOT NULL,
    [FK_CANTON]         INT            NOT NULL,
    [FK_DISTRITO]       INT            NOT NULL,
    [FK_TIPO_AVERIA]    INT            NOT NULL,
    [DIRECCION_EXACTA]  NVARCHAR (250) NULL,
    [LATITUD]           FLOAT (53)     NULL,
    [LONGITUD]          FLOAT (53)     NULL,
    [NIS]               INT            NULL,
    [NOMBRE]            NVARCHAR (15)  NULL,
    [PRIMERAPELLIDO]    NVARCHAR (15)  NULL,
    [SEGUNDOAPELLIDO]   NVARCHAR (15)  NULL,
    [EMAIL]             NVARCHAR (100) NULL,
    [DESCRIPCION]       NVARCHAR (500) NULL,
    [TELEFONO]          NVARCHAR (20)  NULL,
    [SINCRONIZADO]      BIT            NULL,
    [STATUS]            CHAR (1)       NULL,
    CONSTRAINT [PK_T_SRV_REPORTE_AVERIA] PRIMARY KEY CLUSTERED ([PK_REPORTE_AVERIA] ASC),
    CONSTRAINT [CHK_STATUS_T_SRV_REPORTE_AVERIA] CHECK ([STATUS]='B' OR [STATUS]='I' OR [STATUS]='A'),
    CONSTRAINT [FK_T_SRV_REPORTE_AVERIA_T_CAT_PROVINCIA] FOREIGN KEY ([FK_PROVINCIA]) REFERENCES [catalogos].[t_cat_provincia] ([PK_PROVINCIA]),
    CONSTRAINT [FK_T_SRV_REPORTE_AVERIA_T_CAT_TIPO_AVERIA] FOREIGN KEY ([FK_TIPO_AVERIA]) REFERENCES [dbo].[t_cat_tipo_averia] ([PK_TIPO_AVERIA])
);

