CREATE TABLE [catalogos].[t_cat_distrito] (
    PK_DISTRITO INT IDENTITY (1,1),
    PK_CANTON INT,
	PK_PROVINCIA INT,
	NOMBRE NVARCHAR(100),
    [STATUS]       BIT            NOT NULL,
	CONSTRAINT PK_T_CAT_DISTRITO PRIMARY KEY (PK_DISTRITO,PK_CANTON,PK_PROVINCIA),
	CONSTRAINT FK_T_CAT_DISTRITO_T_CAT_CANTON FOREIGN KEY (PK_CANTON,PK_PROVINCIA) REFERENCES [catalogos].[t_cat_canton] (PK_CANTON,PK_PROVINCIA)
);

