CREATE TABLE [catalogos].[t_cat_canton] (
    PK_CANTON INT IDENTITY (1,1),
    PK_PROVINCIA INT,
    NOMBRE NVARCHAR(100),
    [STATUS]       BIT            NOT NULL,
	CONSTRAINT PK_T_CAT_CANTON PRIMARY KEY (PK_CANTON,PK_PROVINCIA),
	CONSTRAINT PK_T_CAT_CANTON_T_CAT_PROVINCIA FOREIGN KEY (PK_PROVINCIA) REFERENCES [catalogos].[t_cat_provincia] (PK_PROVINCIA)
);

