CREATE TABLE [catalogos].[t_cat_tipo_uso] (
    [PK_TIPO_USO] INT            IDENTITY (1, 1) NOT NULL,
    [DESCRIPCION] NVARCHAR (100) NULL,
    [STATUS]      BIT            NOT NULL,
    CONSTRAINT [PK_T_CAT_TIPO_USO] PRIMARY KEY CLUSTERED ([PK_TIPO_USO] ASC)
);



