CREATE TABLE [seguridad].[t_seg_operacion] (
    [PK_OPERACION] INT            IDENTITY (1, 1) NOT NULL,
    [NOMBRE]       NVARCHAR (100) NOT NULL,
    [STATUS]       BIT            NOT NULL,
    CONSTRAINT [PK_OPERACION] PRIMARY KEY CLUSTERED ([PK_OPERACION] ASC)
);

